"""
Token encryption utilities for Euterpe

All Spotify OAuth tokens MUST be encrypted at rest.
Uses Fernet symmetric encryption (AES-128 in CBC mode with HMAC).

SECURITY REQUIREMENTS:
- ENCRYPTION_KEY must be set in environment variables
- Key must be 32 url-safe base64-encoded bytes (generated by Fernet.generate_key())
- Never log or expose decrypted tokens
"""

import os
from cryptography.fernet import Fernet


def get_encryption_key():
    """
    Get encryption key from environment variable.
    
    Returns:
        bytes: The encryption key
        
    Raises:
        ValueError: If ENCRYPTION_KEY is not set
    """
    key = os.environ.get('ENCRYPTION_KEY')
    if not key:
        raise ValueError(
            "ENCRYPTION_KEY environment variable not set. "
            "Generate one with: python -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())'"
        )
    return key.encode()


def encrypt_token(token):
    """
    Encrypt a token for storage.
    
    Args:
        token (str): The plaintext token to encrypt
        
    Returns:
        str: The encrypted token (base64-encoded)
    """
    if not token:
        raise ValueError("Cannot encrypt empty token")
    
    f = Fernet(get_encryption_key())
    encrypted = f.encrypt(token.encode())
    return encrypted.decode()


def decrypt_token(encrypted_token):
    """
    Decrypt a stored token.
    
    Args:
        encrypted_token (str): The encrypted token from database
        
    Returns:
        str: The decrypted plaintext token
        
    Raises:
        cryptography.fernet.InvalidToken: If decryption fails
    """
    if not encrypted_token:
        raise ValueError("Cannot decrypt empty token")
    
    f = Fernet(get_encryption_key())
    decrypted = f.decrypt(encrypted_token.encode())
    return decrypted.decode()


def generate_key():
    """
    Generate a new encryption key.
    
    Returns:
        str: A new Fernet key suitable for ENCRYPTION_KEY environment variable
    """
    return Fernet.generate_key().decode()


if __name__ == '__main__':
    # Allow running this script to generate a new key
    print("Generated ENCRYPTION_KEY:")
    print(generate_key())
    print("\nAdd this to your Heroku config:")
    print("heroku config:set ENCRYPTION_KEY='<key above>'")

